# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ACXaWHt_3i3gqidqQmMmiL_VP4AOMDWz
"""

# ==========================================
# CodeAlpha Task 4
# Sales Prediction using Python
# ==========================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# ------------------------------------------
# Load Dataset
# ------------------------------------------

df = pd.read_csv("/content/dataset3.csv.zip")

# Display first 5 rows
print("First 5 Rows")
print(df.head())

# Dataset Information
print("\nDataset Information")
print(df.info())

# Missing Values
print("\nMissing Values")
print(df.isnull().sum())

# Remove unwanted index column if present
if "Unnamed: 0" in df.columns:
    df.drop("Unnamed: 0", axis=1, inplace=True)

# ------------------------------------------
# Statistical Summary
# ------------------------------------------

print("\nStatistical Summary")
print(df.describe())

# ------------------------------------------
# Correlation Heatmap
# ------------------------------------------

plt.figure(figsize=(7,5))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

# ------------------------------------------
# Pair Plot
# ------------------------------------------

sns.pairplot(df)
plt.show()

# ------------------------------------------
# Features and Target
# ------------------------------------------

X = df[['TV', 'Radio', 'Newspaper']]
y = df['Sales']

# ------------------------------------------
# Split Dataset
# ------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# ------------------------------------------
# Train Model
# ------------------------------------------

model = LinearRegression()
model.fit(X_train, y_train)

# ------------------------------------------
# Predict Sales
# ------------------------------------------

y_pred = model.predict(X_test)

# ------------------------------------------
# Model Evaluation
# ------------------------------------------

print("\nModel Performance")

print("R2 Score :", r2_score(y_test, y_pred))
print("MAE      :", mean_absolute_error(y_test, y_pred))
print("MSE      :", mean_squared_error(y_test, y_pred))

# ------------------------------------------
# Actual vs Predicted
# ------------------------------------------

result = pd.DataFrame({
    "Actual Sales": y_test.values,
    "Predicted Sales": y_pred
})

print("\nActual vs Predicted Sales")
print(result.head(10))

# ------------------------------------------
# Scatter Plot
# ------------------------------------------

plt.figure(figsize=(7,5))
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Sales")
plt.ylabel("Predicted Sales")
plt.title("Actual vs Predicted Sales")
plt.grid(True)
plt.show()

# ------------------------------------------
# Feature Importance
# ------------------------------------------

importance = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

print("\nFeature Importance")
print(importance)

plt.figure(figsize=(6,4))
plt.bar(importance["Feature"], importance["Coefficient"])
plt.title("Advertising Feature Importance")
plt.xlabel("Advertising Platform")
plt.ylabel("Coefficient")
plt.show()

print("\nSales Prediction Completed Successfully!")